---
title: "amar.ficherselection"
author: "luka"
date: "2025-02-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
clean_data <- read_csv("C:/Users/USER/Downloads/clean_data.csv")
data <- clean_data 
```



```{r}
# بارگذاری کتابخانه‌های مورد نیاز
library(dplyr)
library(randomForest)

# حذف ستون های اول و دوم
data <- data[, -c(1, 2)]

# تبدیل ستون های غیر عددی به عوامل (فاکتورها)
data[] <- lapply(data, function(x) if(is.character(x)) as.factor(x) else x)

# مدیریت مقادیر گم شده با جایگزینی میانگین ستون ها
for(i in seq_along(data)) {
  if(is.numeric(data[[i]])) {
    data[[i]][is.na(data[[i]])] <- mean(data[[i]], na.rm = TRUE)
  }
}

# کاهش تعداد دسته های پیش بینی گرهای دسته ای بزرگتر
data[] <- lapply(data, function(x) if(is.factor(x) && nlevels(x) > 53) {
  levels_to_keep <- names(sort(table(x), decreasing = TRUE)[1:53])
  x <- factor(ifelse(x %in% levels_to_keep, as.character(x), "Other"))
  return(x)
} else return(x))

# تعیین متغیر هدف
target <- data$Amtiaz

# حذف ستون متغیر هدف از مجموعه ویژگی ها
features <- data[, !names(data) %in% 'Amtiaz']

# آموزش مدل جنگل تصادفی و محاسبه اهمیت ویژگی ها
rf_model <- randomForest(features, target, importance = TRUE, na.action = na.omit)

# استخراج اهمیت ویژگی ها
importance <- importance(rf_model)
importance_df <- data.frame(Feature = rownames(importance), Importance = importance[, 1])

# مرتب سازی ویژگی ها بر اساس اهمیت
importance_df <- importance_df[order(-importance_df$Importance), ]

# نمایش ویژگی های مهم
print("Feature Importance:")
print(importance_df)

# انتخاب n ویژگی برتر (مثلاً 10 ویژگی برتر)
top_n <- 10
top_features <- importance_df$Feature[1:top_n]

# ایجاد مجموعه داده جدید با ویژگی های مهم
final_data <- data[, c(top_features, 'Amtiaz')]
desktop_path <- file.path(Sys.getenv("USERPROFILE"), "Desktop", "final_data")

# ذخیره اطلاعات در فایل CSV در دسکتاپ
write_csv(final_data, desktop_path)

# نمایش پیام تایید
print("اطلاعات با موفقیت در فایل CSV در دسکتاپ ذخیره شد.")

```

